<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpPRxYe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpPRxYe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpPRxYe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpPRxYe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRpPRxYe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RpPRxYe',
    'container.build_id' => '7d4b5a24',
    'container.build_time' => 1567758723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpPRxYe');
